<?xml version="1.0" encoding="UTF-8"?>
<!--
  ============================================================================
  Lagrange Tactical AI - Battle Report XSLT Transformation
  Transforms battle report XML into HTML for web display.
  ============================================================================
-->
<xsl:stylesheet version="1.0"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:lag="http://lagrange.ai/battle-report">

  <xsl:output method="html" indent="yes" encoding="UTF-8" />
  <xsl:param name="cssPath" select="'/static/styles/report.css'" />

  <!-- ===== Root Template ===== -->
  <xsl:template match="/lagrange_battle_report">
    <html lang="zh-CN">
      <head>
        <meta charset="UTF-8" />
        <title>Battle Report - <xsl:value-of select="meta/battle_id" /></title>
        <link rel="stylesheet" href="{$cssPath}" />
        <style>
          body { font-family: 'Segoe UI', 'Microsoft YaHei', sans-serif;
                 background: #0a0e1a; color: #d0d8f0; padding: 20px; }
          h1 { color: #60a5fa; text-align: center; }
          .report-section { background: #111827; border: 1px solid #1e3a8a;
                            border-radius: 8px; padding: 18px; margin: 16px 0; }
          h2 { color: #60a5fa; font-size: 16px; border-bottom: 1px solid #1e293b;
               padding-bottom: 8px; margin-bottom: 12px; }
          table { width: 100%; border-collapse: collapse; font-size: 13px; }
          th { background: #1e293b; color: #60a5fa; padding: 10px 8px;
               text-align: left; font-size: 11px; text-transform: uppercase; }
          td { padding: 8px; border-bottom: 1px solid #1e293b; }
          .outcome { text-align: center; padding: 16px; border-radius: 8px;
                     margin: 12px 0; font-size: 22px; font-weight: bold; }
          .outcome.victory { background: #064e3b33; color: #22c55e; border: 1px solid #22c55e; }
          .outcome.defeat { background: #7f1d1d33; color: #ef4444; border: 1px solid #ef4444; }
          .outcome.draw { background: #713f1233; color: #f59e0b; border: 1px solid #f59e0b; }
          .ai-box { border-left: 3px solid #8b5cf6; padding: 12px; margin: 8px 0; }
          .footer { text-align: center; font-size: 11px; color: #64748b;
                    padding: 12px; border-top: 1px solid #1e293b; margin-top: 20px; }
        </style>
      </head>
      <body>
        <h1>Fleet Battle Report</h1>

        <!-- Meta -->
        <div class="report-section">
          <h2>Report Info</h2>
          <table>
            <tr>
              <th>Generated</th><td><xsl:value-of select="meta/generated_at" /></td>
              <th>Engine</th><td>v<xsl:value-of select="meta/engine_version" /></td>
            </tr>
            <tr>
              <th>Battle ID</th><td><xsl:value-of select="meta/battle_id" /></td>
              <th>Seed</th><td><xsl:value-of select="meta/seed" /></td>
            </tr>
          </table>
        </div>

        <!-- Outcome -->
        <xsl:apply-templates select="battle_result/outcome" mode="banner" />

        <!-- Fleets -->
        <xsl:apply-templates select="fleets" />

        <!-- Battle Statistics -->
        <xsl:apply-templates select="battle_result" />

        <!-- AI Analysis -->
        <xsl:apply-templates select="ai_analysis" />

        <!-- Footer -->
        <div class="footer">
          Generated by Lagrange Tactical AI v<xsl:value-of select="meta/engine_version" />
          | <xsl:value-of select="meta/generated_at" />
        </div>
      </body>
    </html>
  </xsl:template>

  <!-- ===== Outcome Banner ===== -->
  <xsl:template match="outcome" mode="banner">
    <div class="outcome {@outcome}">
      <xsl:value-of select="translate(@outcome, 'abcdfeghijklmnopqrstuvwxyz',
                                       'ABCDEFGHIJKLMNOPQRSTUVWXYZ')" />
      - Fleet <xsl:value-of select="../winner_fleet" />
    </div>
  </xsl:template>

  <!-- ===== Fleets Display ===== -->
  <xsl:template match="fleets">
    <div class="report-section">
      <h2>Fleet Composition</h2>
      <xsl:for-each select="fleet">
        <div style="margin-bottom: 16px;">
          <h3 style="color: #93c5fd;">
            <xsl:value-of select="name" />
            (<xsl:value-of select="@side" />)
            - <xsl:value-of select="count(ships/ship)" /> ships
          </h3>
          <table>
            <thead>
              <tr>
                <th>Ship</th><th>Class</th><th>Tier</th><th>HP</th>
                <th>Armor</th><th>Shield</th><th>DPS</th>
              </tr>
            </thead>
            <tbody>
              <xsl:for-each select="ships/ship">
                <tr>
                  <td><strong><xsl:value-of select="@name" /></strong></td>
                  <td><xsl:value-of select="ship_class" /></td>
                  <td><xsl:value-of select="@tier" /></td>
                  <td><xsl:value-of select="stats/hp" /></td>
                  <td><xsl:value-of select="stats/armor" /></td>
                  <td><xsl:value-of select="stats/shield" /></td>
                  <td><xsl:value-of select="stats/weapon_dps" /></td>
                </tr>
              </xsl:for-each>
            </tbody>
          </table>

          <!-- Ship Weapons -->
          <xsl:for-each select="ships/ship[weapons]">
            <h4 style="color: #60a5fa; font-size: 12px; margin: 10px 0 4px;">
              <xsl:value-of select="@name" /> Weapon Systems
            </h4>
            <table>
              <tr>
                <th>Weapon</th><th>Type</th><th>Damage</th><th>Range</th><th>Slots</th>
              </tr>
              <xsl:for-each select="weapons/weapon">
                <tr>
                  <td><xsl:value-of select="@name" /></td>
                  <td><xsl:value-of select="type" /></td>
                  <td><xsl:value-of select="@damage" /></td>
                  <td><xsl:value-of select="range" /></td>
                  <td><xsl:value-of select="slot_count" /></td>
                </tr>
              </xsl:for-each>
            </table>
          </xsl:for-each>
        </div>
      </xsl:for-each>
    </div>
  </xsl:template>

  <!-- ===== Battle Statistics ===== -->
  <xsl:template match="battle_result">
    <div class="report-section">
      <h2>Battle Statistics</h2>
      <table>
        <tr>
          <th>Duration</th><td><xsl:value-of select="duration" />s</td>
          <th>Rounds</th><td><xsl:value-of select="total_rounds" /></td>
        </tr>
        <tr>
          <th>Total Damage</th><td><xsl:value-of select="total_damage" /></td>
          <th>Ships Lost</th><td><xsl:value-of select="total_ships_lost" /></td>
        </tr>
        <tr>
          <th>Hit Rate</th><td><xsl:value-of select="hit_rate" />%</td>
          <th>Winner</th><td><xsl:value-of select="winner_fleet" /></td>
        </tr>
      </table>
    </div>

    <!-- Ship Performance -->
    <xsl:if test="ship_performances">
      <div class="report-section">
        <h2>Ship Performance</h2>
        <table>
          <thead>
            <tr>
              <th>Ship</th><th>Kills</th><th>Losses</th>
              <th>Damage Dealt</th><th>Damage Taken</th><th>Survived</th>
            </tr>
          </thead>
          <tbody>
            <xsl:for-each select="ship_performances/ship_performance">
              <tr>
                <td><xsl:value-of select="@ship_ref" /></td>
                <td><xsl:value-of select="kills" /></td>
                <td><xsl:value-of select="losses" /></td>
                <td><xsl:value-of select="damage_dealt" /></td>
                <td><xsl:value-of select="damage_taken" /></td>
                <td><xsl:value-of select="survived" /></td>
              </tr>
            </xsl:for-each>
          </tbody>
        </table>
      </div>
    </xsl:if>
  </xsl:template>

  <!-- ===== AI Analysis ===== -->
  <xsl:template match="ai_analysis">
    <div class="report-section">
      <h2>AI Tactical Analysis</h2>
      <p><xsl:value-of select="summary" /></p>
      <xsl:if test="recommendations">
        <xsl:for-each select="recommendations/recommendation">
          <div class="ai-box">
            <strong><xsl:value-of select="@priority" />:</strong>
            <xsl:value-of select="text" />
          </div>
        </xsl:for-each>
      </xsl:if>
    </div>
  </xsl:template>

</xsl:stylesheet>
